# Site settings
title: Rizal Asrul Pambudi
subtitle: sharing will enrich everyone with more knowledge
email: rizal.asrul@live.com
description: > # this means to ignore newlines until "baseurl:"
  Sebuah tempat berbagi tulisan oleh Rizal Asrul Pambudi
baseurl:  # the subpath of your site, e.g. /blog/
url:  https://rizalasrul.github.io
twitter_username: asrulole
github_username:  rizalasrul
linkedin_username:  rizalasrul
instagram_username:  rizalasrul
facebook_username:  rizal.asrul

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/
  post:
    output: true
    permalink: /:path/

